### ISSUE TITLE
lovr-ui in fuse mode

### ISSUE THREAD

**Issue by fendrin** [immortalx74/lovr-ui#10]
I get:
```
Error:
utils/ui/ui.lua:827: Could not read Font from 'ui/DejaVuSansMono.ttf'
```

The path it should read from is 'utils/ui/DejaVuSansMono.ttf'

To me it seems like
```
local root = (...):match( '(.-)[^%./]+$' ):gsub( '%.', '/' )
```
is not working like expected in fuse mode.

Regards, Fabi

**Comment by fendrin** [comment]
I have learned that it is not the fuse mode but how the module is required.
So the ui currently does not support require paths properly.
It works if required with the complete path.

**Comment by immortalx74** [comment]
Thanks for the report Fabi. Bjorn did a PR which hopefully fixes that.

**Comment by fendrin** [comment]
You are welcome.
Surprisingly fast reaction, I am impressed.
Will test it soon.

**Comment by fendrin** [comment]
Works for me now as well.
Thank you.
