### ISSUE TITLE
Duplicate widget name not allowd within a frame

### ISSUE THREAD

**Issue by jmiskovic** [immortalx74/lovr-ui#12]
When re-using the same name for another widget some weird behavior comes up, like sliders affecting each other. I think this is common enough occurrence in general UIs that it should be supported (or documented as limitation).

**Comment by immortalx74** [comment]
It is (currently) indeed a limitation, sorry for not documenting this. Widgets are identified by doing a hash on their name. The proper solution (like Dear ImGui does) is to parse the name and check for ,say, a double hash symbol(##). Include the whole string for hashing but drop any characters after '##' when rendering the text.
So then you can have 2 buttons display "Click Me" but their actual names would be e.g. "Click Me##1", "Click Me##2".

Thanks for opening this, I will implemented it soon!

**Comment by jmiskovic** [comment]
I worked around it by adding a widget-counter to hashed string, incremented inside the `UpdateLayout`.
Is there a reason why names should be unique on the user side? Or just internal handling?

**Comment by immortalx74** [comment]
Hmm, maybe your workaround is better and simpler. If you don't mind sharing it I could implement this instead.

**Comment by jmiskovic** [comment]
The code I'm using is this:
https://github.com/immortalx74/lovr-ui/pull/13

Not necessary the best as I didn't go through the library design too carefully.
