### ISSUE TITLE
Support for third-party widgets

### ISSUE THREAD

**Issue by brainrom** [immortalx74/lovr-ui#14]
This can be done at least two ways:
1. Placing local fields of UI in special private field, `_`, `private`, etc., and loading widgets via extending UI table by `UI.CustomWidget = function() ... end`
2. Inlining lovr-ui with custom widget `UI = loadstring(lovr.filesystem.read("lovr-ui/ui/ui.lua") .. lovr.filesystem.read("customwidget.lua"))()` 

First option is better, because it allows to add widget at runtime, and give a meaningful debug info on stacktrace, but require more rework in lovr-ui core. Second option easier to implement, but UI table becomes a black box.

**Comment by immortalx74** [comment]
Thanks for the suggestion, sounds like a nice idea (especially the first one)! Do you have any working implementation?

**Comment by brainrom** [comment]
I implemented second option, but it's not so cool, so now I'm working on the first option.

**Comment by brainrom** [comment]
For obvious reasons, I had to change almost every line. I tested on the example of lovr-ui that I didn't break anything, but please do the tests too.

**Comment by immortalx74** [comment]
I see no issues, everything seems fine and thanks for your hard work. If you also have an example of user-defined widget it would be nice to share.

**Comment by brainrom** [comment]
Actually, any "default" widget can be used as module (and lovr-ui can be split into files). Lua module should return function object. I'll make CustomDummy example.

**Comment by brainrom** [comment]
```
function Widget( width, height )
    local _ = UI._
    local bbox = {}
    if _.layout.same_line then
        bbox = { x = _.layout.prev_x + _.layout.prev_w + _.margin, y = _.layout.prev_y, w = width, h = height }
    else
        bbox = { x = _.margin, y = _.layout.prev_y + _.layout.row_h + _.margin, w = width, h = height }
    end

    _.UpdateLayout( bbox )
end

return Widget
```

Dummy widget, extracted as user-defined. But I dunno, where to add it as an example.
