### ISSUE TITLE
Consider adding a special case for headset emulation with mouse and keyboard

### ISSUE THREAD

**Issue by Calandiel** [immortalx74/lovr-ui#7]
Hello! I've tried your library and while it seems to work great, I think it falls a bit short when LOVR emulates a headset with mouse and keyboard. The "pointer" never goes out of focus after the initial right click is pressed and in combination with having to hold left click to rotate the camera it feels really awkward. I think the experience could easily be improved by adding a special case in `UI.InputInfo` that captures data from the head instead of the dominant hand when the headset is emulated. Perhaps something along the lines of 
```lua
	if emulated_headset then
		ray.pos = vec3(lovr.headset.getPosition("head"))
		ray.ori = quat(lovr.headset.getOrientation("head"))
		local m = mat4(vec3(0, 0, 0), ray.ori):rotate(0, 1, 0, 0)
		ray.dir = quat(m):direction()
	else
		ray.pos = vec3(lovr.headset.getPosition(dominant_hand))
		ray.ori = quat(lovr.headset.getOrientation(dominant_hand))
		local m = mat4(vec3(0, 0, 0), ray.ori):rotate(-input.pointer_rotation, 1, 0, 0)
		ray.dir = quat(m):direction()
	end
```
instead of the current calculations. This reproduces behavior more similar to that of normal first person games, wherein the ray is cast in the view direction from the middle of the screen.
If that's something you think fits the design of the library, I can create a pull request (I've already got it working in my local fork), if not, close this issue please, it is more of a suggestion than a bug report ^-^

**Comment by immortalx74** [comment]
Great suggestion! Please do the PR, it would be more than welcome.
